# Generated by Django 5.2.4 on 2025-08-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_address_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_per_unit',
        ),
    ]
